"""Reusable summarize-and-persist core for a ``workspace_items`` row.

The artifact_summarizer agent produces an agent-facing coverage summary for a
published workspace item. Historically that summary was generated by exactly
one caller — the Postgres ``AFTER INSERT`` trigger on ``workspace_items``,
which POSTs to ``POST /internal/summarize-workspace-item`` (see
``backend/app/api/internal_webhooks.py``).

This module extracts that summarize-and-persist logic into a plain awaitable
function so any in-process code path can invoke it inline. The webhook now
delegates here; the new inline OCR path (a separate plan) calls it too.

Best-effort by contract: every failure path is caught, logged at WARNING, and
turned into a ``False`` return. The function never raises into its callers —
neither the fire-and-forget DB trigger nor a user-facing chat turn should be
broken by a summarize hiccup.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone

from supabase import Client as SupabaseClient

from agents.memory.artifact_summarizer import (
    ArtifactSummaryInput,
    ArtifactSummaryOutput,
    AttachmentSummaryInput,
    AttachmentSummaryOutput,
    build_artifact_summary_deps,
    run_artifact_summary,
    run_attachment_summary,
)
from agents.runs import AgentRunRecord, record_agent_run
from agents.utils.tracking import track_stage
from shared.observability import get_logfire

logger = logging.getLogger(__name__)
_logfire = get_logfire()

# How much conversation context the attachment flow feeds the summarizer.
# Deliberately small (the "start small" decision in the seed plan): the most
# recent handful of messages plus, when present, the latest convo_context
# compaction summary. Each message body is clipped so a long turn cannot
# dominate the prompt.
ATTACHMENT_CONTEXT_MESSAGE_COUNT = 6
ATTACHMENT_CONTEXT_MESSAGE_CLIP_CHARS = 600
ATTACHMENT_CONTEXT_COMPACTION_CLIP_CHARS = 1500


# Below this many characters of content_md, we skip the LLM entirely and leave
# summary = NULL. Matches the same gate enforced by the Postgres trigger (see
# migration 041) — kept here as defense in depth in case this function is
# reached via a path that bypasses the trigger (manual POST, backfill script,
# the inline OCR path).
MIN_CONTENT_LENGTH_CHARS = 300


# ---------------------------------------------------------------------------
# Persistence helpers
# ---------------------------------------------------------------------------


def _persist_summary(
    supabase: SupabaseClient,
    item_id: str,
    summary: ArtifactSummaryOutput,
    source_length: int,
    existing_metadata: dict,
) -> None:
    """UPDATE workspace_items with the summary + telemetry. Best-effort."""
    metadata = dict(existing_metadata or {})
    metadata["artifact_summary"] = {
        "model_used": summary.model_used,
        "tokens_in": summary.tokens_in,
        "tokens_out": summary.tokens_out,
        "tokens_reasoning": summary.tokens_reasoning,
        "fallback_used": summary.fallback_used,
    }
    try:
        (
            supabase.table("workspace_items")
            .update({
                "summary": summary.summary_md,
                "summary_updated_at": datetime.now(timezone.utc).isoformat(),
                "summary_source_length": source_length,
                "metadata": metadata,
            })
            .eq("item_id", item_id)
            .execute()
        )
    except Exception as exc:  # noqa: BLE001
        logger.warning(
            "summarize_workspace_item: UPDATE failed for item_id=%s: %s",
            item_id, exc, exc_info=True,
        )


def _record_cost(
    supabase: SupabaseClient,
    row: dict,
    summary: ArtifactSummaryOutput,
) -> None:
    """Record a tier_2 agent_runs row. Skipped if the LLM never ran."""
    if summary.fallback_used:
        return
    try:
        record_agent_run(
            supabase,
            AgentRunRecord(
                user_id=str(row.get("user_id") or ""),
                conversation_id=str(row.get("conversation_id") or ""),
                case_id=row.get("case_id") and str(row["case_id"]) or None,
                agent_family="memory",
                subtype="summarize_artifact",
                output_item_id=str(row.get("item_id") or ""),
                tokens_in=summary.tokens_in,
                tokens_out=summary.tokens_out,
                tokens_reasoning=summary.tokens_reasoning,
                model_used=summary.model_used or None,
                per_phase_stats={
                    "summarize": {
                        "per_tier": {
                            "tier_2": {
                                "input": summary.tokens_in,
                                "output": summary.tokens_out,
                                "reasoning": summary.tokens_reasoning,
                                "cached": getattr(summary, "tokens_cached", 0),
                            },
                        },
                    },
                },
                status="ok",
            ),
        )
    except Exception as exc:  # noqa: BLE001
        logger.warning(
            "summarize_workspace_item: record_agent_run failed: %s", exc,
        )


# ---------------------------------------------------------------------------
# Attachment flow — context loading + persistence
# ---------------------------------------------------------------------------


def _load_conversation_context(
    supabase: SupabaseClient,
    conversation_id: str,
) -> str:
    """Build a small conversation-context blob for the attachment flow.

    Two cheap sources, both best-effort:

    * the latest ``convo_context`` workspace item's ``content_md`` (the memory
      compaction summary, when one exists);
    * the most recent ``ATTACHMENT_CONTEXT_MESSAGE_COUNT`` chat messages.

    Each piece is clipped so a long document or a long turn cannot dominate
    the summarizer prompt. Returns an empty string when nothing is available
    or every lookup fails — the prompt handles "no context" gracefully.
    """
    if not conversation_id:
        return ""

    parts: list[str] = []

    # --- Latest convo_context compaction summary ---------------------------
    try:
        ctx_resp = (
            supabase.table("workspace_items")
            .select("content_md, created_at")
            .eq("conversation_id", conversation_id)
            .eq("kind", "convo_context")
            .is_("deleted_at", "null")
            .order("created_at", desc=True)
            .limit(1)
            .execute()
        )
        ctx_rows = (ctx_resp.data or []) if ctx_resp else []
        if ctx_rows:
            compaction = (ctx_rows[0].get("content_md") or "").strip()
            if compaction:
                clipped = compaction[:ATTACHMENT_CONTEXT_COMPACTION_CLIP_CHARS]
                parts.append(f"## ملخّص سياق المحادثة السابق\n{clipped}")
    except Exception as exc:  # noqa: BLE001
        logger.warning(
            "summarize_workspace_item: convo_context load failed for "
            "conversation_id=%s: %s",
            conversation_id, exc,
        )

    # --- Most recent chat messages -----------------------------------------
    try:
        msg_resp = (
            supabase.table("messages")
            .select("role, content, created_at")
            .eq("conversation_id", conversation_id)
            .order("created_at", desc=True)
            .limit(ATTACHMENT_CONTEXT_MESSAGE_COUNT)
            .execute()
        )
        msg_rows = (msg_resp.data or []) if msg_resp else []
        # Fetched newest-first for the LIMIT; render oldest-first for reading.
        msg_rows = list(reversed(msg_rows))
        lines: list[str] = []
        for row in msg_rows:
            content = (row.get("content") or "").strip()
            if not content:
                continue
            role = str(row.get("role") or "").strip() or "?"
            clipped = content[:ATTACHMENT_CONTEXT_MESSAGE_CLIP_CHARS]
            lines.append(f"[{role}] {clipped}")
        if lines:
            parts.append("## أحدث رسائل المحادثة\n" + "\n".join(lines))
    except Exception as exc:  # noqa: BLE001
        logger.warning(
            "summarize_workspace_item: recent messages load failed for "
            "conversation_id=%s: %s",
            conversation_id, exc,
        )

    return "\n\n".join(parts).strip()


def _persist_attachment_summary(
    supabase: SupabaseClient,
    item_id: str,
    summary: AttachmentSummaryOutput,
    source_length: int,
    existing_metadata: dict,
) -> None:
    """UPDATE workspace_items with the attachment title + summary + telemetry.

    Unlike the generic flow, this also updates ``title`` — the attachment
    flow's whole point is to replace the raw upload filename with a grounded
    title. Best-effort: a failed write is logged, never raised.
    """
    metadata = dict(existing_metadata or {})
    metadata["artifact_summary"] = {
        "flow": "attachment",
        "model_used": summary.model_used,
        "tokens_in": summary.tokens_in,
        "tokens_out": summary.tokens_out,
        "tokens_reasoning": summary.tokens_reasoning,
        "fallback_used": summary.fallback_used,
        "context_link": summary.context_link or "",
    }
    update: dict = {
        "summary": summary.summary_md,
        "summary_updated_at": datetime.now(timezone.utc).isoformat(),
        "summary_source_length": source_length,
        "metadata": metadata,
    }
    # Only overwrite the title when the flow produced a non-empty one — never
    # blank out an existing filename.
    new_title = (summary.title or "").strip()
    if new_title:
        update["title"] = new_title
    try:
        (
            supabase.table("workspace_items")
            .update(update)
            .eq("item_id", item_id)
            .execute()
        )
    except Exception as exc:  # noqa: BLE001
        logger.warning(
            "summarize_workspace_item: attachment UPDATE failed for "
            "item_id=%s: %s",
            item_id, exc, exc_info=True,
        )


def _record_attachment_cost(
    supabase: SupabaseClient,
    row: dict,
    summary: AttachmentSummaryOutput,
) -> None:
    """Record a tier_2 agent_runs row for the attachment flow.

    Skipped when the LLM never ran (fallback). Subtype ``summarize_attachment``
    distinguishes it from the generic ``summarize_artifact`` runs.
    """
    if summary.fallback_used:
        return
    try:
        record_agent_run(
            supabase,
            AgentRunRecord(
                user_id=str(row.get("user_id") or ""),
                conversation_id=str(row.get("conversation_id") or ""),
                case_id=row.get("case_id") and str(row["case_id"]) or None,
                agent_family="memory",
                subtype="summarize_attachment",
                output_item_id=str(row.get("item_id") or ""),
                tokens_in=summary.tokens_in,
                tokens_out=summary.tokens_out,
                tokens_reasoning=summary.tokens_reasoning,
                model_used=summary.model_used or None,
                per_phase_stats={
                    "summarize": {
                        "per_tier": {
                            "tier_2": {
                                "input": summary.tokens_in,
                                "output": summary.tokens_out,
                                "reasoning": summary.tokens_reasoning,
                                "cached": getattr(summary, "tokens_cached", 0),
                            },
                        },
                    },
                },
                status="ok",
            ),
        )
    except Exception as exc:  # noqa: BLE001
        logger.warning(
            "summarize_workspace_item: attachment record_agent_run failed: %s",
            exc,
        )


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


async def summarize_workspace_item(
    supabase: SupabaseClient,
    item_id: str,
    *,
    force: bool = False,
) -> bool:
    """Generate + persist an agent-facing summary for a workspace item.

    Re-fetches the ``workspace_items`` row by ``item_id`` (rather than trusting
    a caller-supplied snapshot, so a summary write that races with another
    UPDATE still sees the current ``content_md``), runs the artifact_summarizer
    agent, writes the result back to ``workspace_items.summary`` +
    ``metadata.artifact_summary``, and records a tier_2 ``agent_runs`` row.

    Guards (any of which → ``return False`` with nothing written):

    * row not found;
    * ``summary`` already set and ``force`` is False (idempotency);
    * ``content_md`` empty (e.g. un-extracted attachment rows);
    * ``len(content_md) < MIN_CONTENT_LENGTH_CHARS`` — short blurbs don't need
      an agent-facing summary; downstream agents read ``content_md`` directly.

    Best-effort: every failure path is caught, logged at WARNING, and turned
    into a ``False`` return. This function never raises.

    Returns ``True`` only when a summary was actually generated and the persist
    path ran; ``False`` when a guard skipped it or an error was swallowed.
    """
    with track_stage(
        "summarize_workspace_item",
        agent_family="memory",
        item_id=item_id,
    ) as _span:
        try:
            # --- Fetch the row ---------------------------------------------
            try:
                resp = (
                    supabase.table("workspace_items")
                    .select("*")
                    .eq("item_id", item_id)
                    .maybe_single()
                    .execute()
                )
            except Exception as exc:  # noqa: BLE001
                logger.warning(
                    "summarize_workspace_item: fetch failed item_id=%s: %s",
                    item_id, exc,
                )
                try:
                    _span.set_outcome("fetch_failed")
                    _span.set(**{
                        "error.type": type(exc).__name__,
                        "error": str(exc),
                    })
                except Exception:
                    pass
                return False

            row = (resp.data or {}) if resp else {}
            if not row:
                try:
                    _span.set_outcome("not_found")
                except Exception:
                    pass
                return False

            # Tag the span with the row's identity now so even early-exit
            # paths surface conversation_id. PII note: user_id deliberately
            # not surfaced — recoverable via Supabase join from item_id.
            try:
                _span.set(**{
                    "conversation_id": str(row.get("conversation_id") or "") or None,
                    "case_id": str(row.get("case_id") or "") or None,
                    "kind": str(row.get("kind") or ""),
                    "content_md_chars": len((row.get("content_md") or "")),
                    "has_describe_query": bool(
                        (row.get("describe_query") or "").strip()
                    ),
                    "force": force,
                })
            except Exception:
                pass

            kind = str(row.get("kind") or "agent_search")

            # --- Guards -----------------------------------------------------
            # Idempotency: skip if already summarized (unless forced).
            if not force and (row.get("summary") or "").strip():
                try:
                    _span.set_outcome("already_summarized")
                except Exception:
                    pass
                return False

            content_md = (row.get("content_md") or "").strip()
            if not content_md:
                # Attachment / empty-body kinds: nothing to summarize.
                try:
                    _span.set_outcome("empty_content_md")
                except Exception:
                    pass
                return False
            if len(content_md) < MIN_CONTENT_LENGTH_CHARS:
                # Below the threshold the LLM call is wasteful — short blurbs
                # don't need an agent-facing summary.
                try:
                    _span.set_outcome("below_min_length")
                except Exception:
                    pass
                return False

            # --- Summarize --------------------------------------------------
            # Two flows, selected by ``kind``. Both use the SAME summarizer
            # agent settings (model, model_settings, retries, usage limits);
            # only the system prompt + output type differ. See the
            # artifact_summarizer package.
            if kind == "attachment":
                # ATTACHMENT FLOW — an OCR-extracted uploaded document. The
                # summarizer produces a grounded title (the raw filename is
                # rarely descriptive) AND a context-aware summary, so it needs
                # a slice of conversation context to relate the document to
                # what the user is asking. Persists BOTH title and summary.
                conversation_context = _load_conversation_context(
                    supabase,
                    str(row.get("conversation_id") or ""),
                )
                try:
                    _span.set(
                        attachment_context_chars=len(conversation_context)
                    )
                except Exception:
                    pass

                att_summary = await run_attachment_summary(
                    AttachmentSummaryInput(
                        filename=str(row.get("title") or ""),
                        content_md=content_md,
                        conversation_context=conversation_context,
                    ),
                    build_artifact_summary_deps(),
                )

                _persist_attachment_summary(
                    supabase,
                    item_id,
                    att_summary,
                    source_length=len(content_md),
                    existing_metadata=row.get("metadata") or {},
                )
                _record_attachment_cost(supabase, row, att_summary)

                try:
                    _span.set_outcome(
                        "ok_fallback" if att_summary.fallback_used else "ok"
                    )
                    _span.set(**{
                        "flow": "attachment",
                        "model_used": att_summary.model_used,
                        "tokens_in": att_summary.tokens_in,
                        "tokens_out": att_summary.tokens_out,
                        "fallback_used": att_summary.fallback_used,
                        "title_chars": len(att_summary.title or ""),
                        "summary_chars": len(att_summary.summary_md or ""),
                    })
                except Exception:
                    pass

                return True

            # GENERIC FLOW — agent-generated artifacts (agent_search, writer,
            # compose_document, ...). The agent reads exactly three columns off
            # the workspace_items row — title, describe_query (router-written
            # query description, migration 038), and content_md. NULL
            # describe_query is fine: the prompt falls back to describing
            # content without a query anchor.
            summary = await run_artifact_summary(
                ArtifactSummaryInput(
                    describe_query=str(row.get("describe_query") or ""),
                    content_md=content_md,
                    title=str(row.get("title") or ""),
                    kind=kind,
                ),
                build_artifact_summary_deps(),
            )

            # --- Persist + record cost (best-effort) ------------------------
            _persist_summary(
                supabase,
                item_id,
                summary,
                source_length=len(content_md),
                existing_metadata=row.get("metadata") or {},
            )
            _record_cost(supabase, row, summary)

            try:
                _span.set_outcome(
                    "ok_fallback" if summary.fallback_used else "ok"
                )
                _span.set(**{
                    "flow": "generic",
                    "model_used": summary.model_used,
                    "tokens_in": summary.tokens_in,
                    "tokens_out": summary.tokens_out,
                    "fallback_used": summary.fallback_used,
                    "summary_chars": len(summary.summary_md or ""),
                })
            except Exception:
                pass

            return True
        except Exception as exc:  # noqa: BLE001
            # Catch-all: this function is best-effort and must never raise
            # into its callers (DB trigger webhook, inline chat-turn path).
            logger.warning(
                "summarize_workspace_item: unexpected failure for item_id=%s: %s",
                item_id, exc, exc_info=True,
            )
            try:
                _span.set_outcome("error")
                _span.set(**{
                    "error.type": type(exc).__name__,
                    "error": str(exc),
                })
            except Exception:
                pass
            return False
