-- ============================================================================
-- 145_related_items_services_and_tiebreak.sql
--   Defect 1: give خدمات a real base axis (services.embedding)
--   Defect 2: break the judgment strip's perfect tie (related_items.tiebreak)
--
-- Plan: .claude/plans/read_next_related_items.md
--       §3 scoring · §3.3 the base contract · §4 the data layer · §7 Wave D
-- Depends on: 143 (APPLIED to prod 2026-08-23 — this file EXTENDS it and never
--             repeats it: the tables, the RLS, the weights builder, the entity
--             alias map, the three أنظمة relation views and the weekly cron job
--             all stay exactly as 143 left them), 142 (public.service_guides /
--             public.services and service_guides.most_used_rank), 111 (house
--             style for refresh_x(corpus) and the guarded pg_cron block).
--
-- LIVE STATE THIS FILE WAS WRITTEN AGAINST — measured on prod 2026-08-23, after
-- 143's backfill, NOT read off a migration file:
--
--   corpus      edges       sources with >= 1
--   regulation     77,612   2,996 of 3,951
--   circular        7,326     375 of 1,843
--   compliance        354      83 of 337        <- Defect 1
--   judgment    1,456,576   4,461 of 30,531     <- Defect 2
--   related_items = ~648 MB including its two indexes (PK + lookup).
--
--
-- ── DEFECT 1 — THE خدمات WING IS STARVED, AND ITS BEST SIGNAL IS UNUSED ─────
-- Only 83 of 337 guides carry any edge at all. The cause is not the floor, it
-- is the SHAPE of the scarcity normalizer: related_target_share() = 0.007 is a
-- FRACTION OF THE CORPUS, and a fraction does not transfer across corpus sizes.
-- On أنظمة (N = 3,951) it means "scarce = 27.7 documents", which is a real
-- population of sectors. On خدمات (N = 337) the same 0.007 means "scarce = 2.4
-- documents" — so virtually no sector clears related_gen_floor() = FLOOR/2 and
-- the generator produces almost nothing. Lowering TARGET_SHARE is not the fix:
-- it is one global knob shared by four corpora, and moving it to suit a
-- 337-document corpus would re-price all 1.5M judgment edges.
--
-- The fix is to stop asking the scarcity axes to carry a wing they cannot
-- carry, and to give خدمات the base axis it has always had and never used:
-- `public.services.embedding` — a 1024-dim vector with an HNSW index
-- (idx_svc_embedding) that every one of the 337 canonical guides reaches
-- through service_guides.service_id. This fills 143's compliance Wave E seam
-- with VECTORS instead of BM25, which is strictly better here: BM25 over
-- search_topics would have been ~1.4 topic sentences per service, while the
-- embedding is a whole-service representation that already exists and is
-- already indexed.
--
--   • FULL PAIRWISE COSINE — no KNN, no top-K. 337 x 336 = 113,232 ordered
--     pairs is ~0.3s of vector arithmetic. A top-K generator would violate D6
--     ("never a top-N per source": a top-10 whose members are all unpublished
--     renders an empty strip while good candidates sit at rank 11+), and at
--     this size there is no reason to reach for one. idx_svc_embedding is NOT
--     used and is not needed — an HNSW index answers "nearest to a probe", and
--     this is an all-pairs scan.
--   • The embedding side EMITS ITS OWN CANDIDATES as well as a base. 143 §0's
--     completeness argument makes the axis generators lossless only for pairs
--     with base = 0; a pair whose base is what carries it over the floor has to
--     be generated by the base side or it is silently lost. 143's compliance
--     `cand` already unions `topic_base`, so this is satisfied by filling the
--     CTE — but it is the reason the CTE must return candidate rows and not
--     just a lookup table of bases.
--   • reason = 'service_embedding', a NEW value — not 'topic_bm25'. They are
--     different evidence and Wave D samples on `reason`. 'topic_bm25' stays
--     reserved for the تعاميم seam, which is still empty.
--
-- ── DEFECT 2 — THE JUDGMENT STRIP IS A PERFECT TIE ─────────────────────────
-- Measured: 22 courts clear related_gen_floor(), and 0 of those 22 contain more
-- than one entity value. Court and entity are therefore both CONSTANT within a
-- court, so bonus = least(2.0, entity_term + w(court)) is constant too, and
-- base is 0 by construction on this corpus. Every candidate for a given
-- judgment scores identically — 0.161 for all 532 others in the largest tax
-- chamber. `order by score desc limit 7` over 532 identical scores returns
-- whatever the planner happens to produce, and it is free to produce something
-- different on the next call: the top 7 is arbitrary AND unstable.
--
-- The fix is a second, separate ordering key: `related_items.tiebreak`, a
-- property of the TARGET normalized to [0,1], higher = shown first. The backend
-- orders by `score desc, tiebreak desc` and the extended lookup index serves
-- that in one scan.
--
-- ⚠ THE TIEBREAK IS NOT FOLDED INTO score. `score = base + bonus` is a
--   production invariant that is verified directly
--   (`abs(score - (base+bonus)) > 0.001` must return 0 rows). Folding a
--   recency term into score would break that check, would make the floor
--   comparison meaningless, and would let a recent-but-weak edge outrank a
--   strong one. It is a separate column and it is only ever an ORDER BY key —
--   nothing thresholds it, so only its monotonicity matters, never its spacing.
--
-- ── WHAT ELSE THIS FILE TOUCHES, AND WHAT IT DOES NOT ──────────────────────
-- Touches: two new knob functions, three new helper functions, one new column,
-- one index redefinition, four comment refreshes, and refresh_related_items()
-- redefined whole. The regulation / circular / judgment branches of that
-- function are byte-identical to 143 apart from what Defect 2 forces (one
-- column in the INSERT list, one expression in the SELECT list, and — on
-- judgment only — a wrapper around the existing `docs` CTE).
-- Does NOT touch: related_axis_weights or its builder (the weights are still
-- correct; خدمات simply stops depending on them alone), related_floor(),
-- related_target_share(), related_gen_floor(), the entity alias map, RLS,
-- grants on the tables, or the weekly cron schedule (same function names, same
-- statements — the compliance statement just does more work now).
--
-- ⚠ خدمات BECOMES THE ONLY CORPUS WHOSE BASE IS AN ABSOLUTE MEASURE. أنظمة
--   bases are absolute-by-construction (fixed tiers 5.0 / 3.5 / [1.5,3.0] /
--   1.2); the plan's §3.3 contract for تعاميم/خدمات is RELATIVE
--   (3.0 * score / max_for_this_source) because it was written for BM25, which
--   is unbounded and whose scale moves with corpus statistics. Cosine
--   similarity is bounded [0,1] and directly comparable across sources, so
--   relative normalization would actively HARM here: it hands base = 3.0 to a
--   guide whose best match is a mediocre 0.51 and ranks it identically to a
--   genuine 0.89 twin pair. §1 uses an absolute two-anchor map instead. That is
--   a property of the signal, not an inconsistency.
--
-- ⚠ COLLISION WARNING — services.embedding IS SCHEDULED FOR DELETION.
--   .claude/plans/reg_search_unified_topics.md D6 lists a coordinated post-soak
--   drop of `services.embedding` + `idx_svc_embedding` (alongside
--   regulation_v2.chunk_titles, chunk_titles_v2, search_chunk_titles() and
--   hybrid_search_services()). After this migration that drop is NO LONGER
--   free: it takes the خدمات base axis with it, and because the weekly cron job
--   runs its five statements in sequence, a "column does not exist" inside the
--   compliance branch aborts the job before the judgment refresh ever starts.
--   If that drop goes ahead, revert §4's compliance `topic_base` to 143's empty
--   stub IN THE SAME CHANGE, or repoint it at search_topics
--   (source_type = 'service', 6,712 rows) first. §0's preflight will at least
--   make the collision loud at apply time rather than at 03:40 on a Sunday.
--
-- ⚠ NO BACKFILL IN THIS FILE — see §6. 143 put its refreshes inline at §9 and
--   that is what makes re-applying it a 13-minute operation. The refreshes here
--   are run BY HAND, in the documented order, and the judgment one has to be a
--   pg_cron one-shot because the Supabase pooler cuts the caller at 120s.
--
-- APPLY COST. `add column ... not null default 0` with a CONSTANT default is
-- metadata-only on PG11+ — no table rewrite, instant, even at 648 MB. The index
-- swap is not free: idx_related_items_lookup is dropped and rebuilt over
-- ~1.54M rows under an ACCESS EXCLUSIVE lock (seconds, not minutes). It is not
-- built CONCURRENTLY because that cannot run inside a transaction block and
-- this file is applied as one script; the alternative — leaving the table
-- unindexed for the duration of a concurrent build — is worse. Reads of
-- related_items block for those seconds; the backend fails soft, so the cost is
-- a missing strip on a page or two.
--
-- Idempotent and re-runnable end to end: add-column-if-not-exists, or-replace
-- functions, a conditional index swap that only fires while the index still has
-- the old shape, and a delete-then-insert refresh.
-- ============================================================================


-- ── 0. PREFLIGHT ───────────────────────────────────────────────────────────
-- Existence and shape only. Every column name in this file is written out
-- literally and never resolved at run time (143's rule: a migration that
-- discovers its own column names cannot be reviewed by reading it, and it turns
-- a pipeline rename from a loud failure into a silent behaviour change). What a
-- bare CREATE would not tell you are the three things checked here, each of
-- which fails SILENTLY otherwise:
--   (a) 143 has not been applied — §3 would then fail on a missing table, but
--       the message would not say why;
--   (b) services.embedding is gone (the D6 drop above) — the compliance branch
--       would compile and then error only when refreshed;
--   (c) the embedding is present but EMPTY for the canonical guides — that
--       produces an empty topic_base, a silently unchanged 83-of-337 wing, and
--       no error at all. This is exactly the regression nobody would notice.
do $$
declare
  v_dim  text;
  v_tot  integer;
  v_emb  integer;
begin
  if to_regclass('public.related_items') is null
     or to_regclass('public.related_axis_weights') is null then
    raise exception
      '145 §0: public.related_items / related_axis_weights missing. Apply '
      '143_related_items.sql FIRST — this migration extends it, it does not '
      'replace it.';
  end if;

  if to_regclass('public.service_guides') is null
     or to_regclass('public.services')    is null
     or to_regclass('public.cases')       is null then
    raise exception
      '145 §0: a corpus relation is missing (need public.service_guides, '
      'public.services, public.cases). Wrong database?';
  end if;

  select format_type(a.atttypid, a.atttypmod)
    into v_dim
    from pg_attribute a
   where a.attrelid = 'public.services'::regclass
     and a.attname  = 'embedding'
     and a.attnum > 0
     and not a.attisdropped;

  if v_dim is null then
    raise exception
      '145 §0: public.services.embedding does not exist. It is the ENTIRE base '
      'axis for خدمات in this migration (§4 compliance branch). If it was '
      'dropped per reg_search_unified_topics D6, revert that branch to 143''s '
      'empty topic_base stub or repoint it at search_topics '
      '(source_type = ''service'') before applying this file.';
  end if;

  -- Coverage. The map is guide -> service -> embedding, INNER at every step:
  -- a guide whose service row vanished has no embedding and simply gets no
  -- topic base (it keeps its sector/entity bonus tier).
  select count(*) into v_tot
    from public.service_guides g
   where coalesce(g.is_canonical, true);

  select count(*) into v_emb
    from public.service_guides g
    join public.services sv on sv.id = g.service_id
   where coalesce(g.is_canonical, true)
     and sv.embedding is not null;

  if v_emb = 0 then
    raise exception
      '145 §0: 0 of % canonical service_guides reach a non-null '
      'services.embedding. topic_base would be empty and the خدمات wing would '
      'stay starved at 83 of 337 sources — silently, with no error.', v_tot;
  end if;

  -- most_used_rank carries the compliance tiebreak (§4). Checked here because a
  -- plpgsql body is only SYNTAX-checked at CREATE time — a missing column
  -- inside it does not surface until the first refresh, and by then the
  -- migration reads as "applied cleanly".
  if not exists (
    select 1 from pg_attribute a
     where a.attrelid = 'public.service_guides'::regclass
       and a.attname  = 'most_used_rank'
       and a.attnum > 0 and not a.attisdropped
  ) then
    raise exception
      '145 §0: public.service_guides.most_used_rank does not exist. It is the '
      'compliance tiebreak (migration 142''s library_compliance_v selects it). '
      'Either re-point §4''s compliance docs CTE or drop to '
      'related_stable_tiebreak(f.b) as regulation/circular do.';
  end if;

  -- Drift is reported, not enforced: the corpus is pipeline-ingested and SHOULD
  -- grow. Read the notice. 2026-08-23 measured 337 / 337 and vector(1024);
  -- most_used_rank had 0 NULLs at wing build (compliance_service_guides §1), and
  -- any that appear now simply sort last.
  raise notice '145 §0: services.embedding is % · canonical guides % · with an '
               'embedding % · unranked (most_used_rank NULL) % '
               '(2026-08-23: vector(1024) · 337 · 337 · 161)',
               v_dim, v_tot, v_emb,
               (select count(*) from public.service_guides g
                 where coalesce(g.is_canonical, true)
                   and g.most_used_rank is null);
end $$;


-- ── 1. THE TWO NEW KNOBS (same discipline as 143 §0) ───────────────────────
-- 143 keeps its calibration constants behind one-line IMMUTABLE functions so a
-- Wave D retune is one edit with no data migration and nothing downstream
-- hardcodes a number. These two follow it exactly. They belong next to
-- related_floor() / related_target_share() conceptually; they live here because
-- 143 is applied and is never edited.
--
-- ── HOW 0.50 WAS CHOSEN — the measured distribution, not a guess ───────────
-- Full pairwise cosine over the 337 canonical guides, 56,616 UNORDERED pairs,
-- measured on prod 2026-08-23:
--
--     p50 0.250 · p90 0.382 · p99 0.559 · p99.9 0.736 · max 0.887
--
-- Coverage and degree at candidate thresholds (directed edges = 2x unordered):
--
--     threshold   guides covered   directed edges   avg degree
--       0.35        337 of 337         17,082          50.7
--       0.40        337                 8,782          26.1
--       0.45        333                 4,600          13.8
--       0.50        310 (92%)           2,432           7.85   <- chosen
--       0.60        229                   692           3.0
--
-- 0.50 keeps 1,216 of 56,616 unordered pairs — 2.15%, i.e. the ~97.9th
-- percentile of the pair distribution, sitting between p90 (0.382) and p99
-- (0.559). (An earlier note called it "just above p99"; the table's own
-- arithmetic says just below. The threshold is right, the label was not.)
--
-- Why that point and not a neighbour:
--   • avg degree 7.85 is the smallest value that still fills the cap of 7 for a
--     typical guide, so the strip is full without storing near-random pairs.
--   • 0.45 buys 23 more covered guides and DOUBLES the edge count with pairs
--     sitting around p95 — that is noise bought at 2x the storage.
--   • 0.60 is honest but thin: 108 guides lose their base axis to gain nothing.
--   • The 27 guides left uncovered at 0.50 are not orphaned. They fall through
--     to the sector/entity bonus tier exactly as they do today.
--
-- ⚠ THE EFFECTIVE FLOOR IS SLIGHTLY HIGHER THAN 0.50 FOR A BONUS-LESS PAIR.
--   §1's map sends 0.50 -> base 0, so a pair with no shared sector or entity
--   needs base >= related_floor() = 0.15 to be STORED, i.e.
--   sim >= 0.50 + 0.15 * (0.887 - 0.50) / 3.0 = 0.5194. Pairs between 0.50 and
--   0.5194 survive only if a sector/entity bonus carries them. Expect the
--   realised coverage to be a little under the 310 measured at the raw cut;
--   §7's first query reports the actual number.
--
-- ⚠ BOTH ANCHORS ARE MODEL-SPECIFIC. They are fitted to the embedding that was
--   in services.embedding on 2026-08-23. Re-embedding the corpus with a
--   different model moves the whole distribution and both numbers must be
--   re-fitted from a fresh percentile dump — a cosine threshold is not
--   portable across embedding spaces the way a rank threshold would be. That
--   trade was taken deliberately: a rank/percentile floor cannot tell a
--   genuinely tight corpus from a genuinely diffuse one, and it would have
--   re-created Defect 1's exact failure (a fraction that does not transfer).

create or replace function public.related_service_sim_floor()
returns real language sql immutable parallel safe as $$
  select 0.50::real;
$$;

comment on function public.related_service_sim_floor() is
  'خدمات base axis: the minimum services.embedding cosine similarity at which a '
  'pair is worth a base at all, and the LOWER anchor of the base map. 0.50 = '
  'the ~97.9th percentile of the 56,616 pairwise similarities measured on prod '
  '2026-08-23 (p50 0.250 / p90 0.382 / p99 0.559 / max 0.887); it covers 310 of '
  '337 guides at avg degree 7.85. Model-specific — re-fit if services.embedding '
  'is ever rebuilt with a different model. Changing it requires re-running '
  'refresh_related_items(''compliance'').';

create or replace function public.related_service_sim_max()
returns real language sql immutable parallel safe as $$
  select 0.887::real;
$$;

comment on function public.related_service_sim_max() is
  'خدمات base axis: the UPPER anchor of the base map — the similarity that '
  'earns the full base of 3.0. 0.887 is the observed corpus maximum on prod '
  '2026-08-23, which also proves no two canonical guides share one '
  'services.embedding (that would read as 1.0). A pair above the anchor is '
  'clamped, so a re-ingest cannot produce a base > 3.0; it would just flatten '
  'the top of the scale, which is the signal to re-fit both anchors.';


-- ── 2. TIEBREAK HELPERS ────────────────────────────────────────────────────
-- Three small functions. All IMMUTABLE and PARALLEL SAFE so they inline into
-- the refresh queries; none carries a `set search_path` clause (that would
-- block inlining) and every reference inside is schema-qualified — same
-- reasoning as 143's related_canonical_entity().

-- 2.1 The Hijri year, mirroring shared/seo/judgment_naming.py:hijri_year().
-- cases.date_hijri is FREE TEXT, not a date: the corpus holds «1445/06/01»,
-- «15 ربيع الأول 1445», «29 ذو القعدة 1443» and bare «1446». The Python side
-- translates Arabic-Indic digits, scans every 4-digit run left to right and
-- takes the first one in the plausible Hijri range 1300–1500. This is the same
-- algorithm, character for character, so a judgment's derived title and its
-- tiebreak can never disagree about what year it is.
--   WITH ORDINALITY is load-bearing: regexp_matches('g') returns a set, and
--   `limit 1` without an explicit order is only accidentally left-to-right.
create or replace function public.related_hijri_year(p_text text)
returns integer language sql immutable parallel safe as $$
  select t.y
    from (
      select (m.arr)[1]::int as y, m.ord
        from regexp_matches(
               translate(coalesce(p_text, ''), '٠١٢٣٤٥٦٧٨٩', '0123456789'),
               '\d{4}', 'g') with ordinality as m(arr, ord)
    ) t
   where t.y between 1300 and 1500
   order by t.ord
   limit 1;
$$;

comment on function public.related_hijri_year(text) is
  'First plausible 4-digit Hijri year (1300–1500) in a free-text date. Mirrors '
  'shared/seo/judgment_naming.py:hijri_year() exactly — Arabic-Indic digits '
  'translated, matches scanned left to right, NULL when none is plausible.';

-- 2.2 Hijri text -> an approximate Gregorian date.
-- G = floor(H - H/33 + 622): 1445 -> 2023, 1300 -> 1882, 1500 -> 2076. Only the
-- YEAR is recoverable, so the date is pinned to 1 July — mid-year is the
-- least-biased choice when the true date is uniform inside the year and has to
-- be compared against rows that DO carry a full date_gregorian.
-- The residual consequence is stated where it matters (§4, judgment branch):
-- every ruling known only to its Hijri year collapses onto one of ~20 dates and
-- those rows tie with each other. That is as much precision as the data holds.
create or replace function public.related_hijri_date(p_text text)
returns date language sql immutable parallel safe as $$
  select make_date(floor(h.y - h.y / 33.0 + 622.0)::int, 7, 1)
    from (select public.related_hijri_year(p_text) as y) h
   where h.y is not null;
$$;

comment on function public.related_hijri_date(text) is
  'Approximate Gregorian date for a free-text Hijri date, pinned to 1 July of '
  'the converted year (G = floor(H - H/33 + 622)). Year precision only — used '
  'as the fallback recency key for the 7,867 judgments that carry date_hijri '
  'but no date_gregorian. NULL in, NULL out.';

-- 2.3 A stable, unbiased shuffle in [0,1) keyed on the target id.
-- This is the tiebreak for أنظمة and تعاميم and it deliberately carries NO
-- signal — see the §4 branch comments for why the two candidates that DO carry
-- signal were both rejected. Its one job is to make the order REPRODUCIBLE:
-- with a constant tiebreak, `order by score desc, tiebreak desc` over a block
-- of equal scores is still whatever the planner returns, and it may return
-- something different next time.
--   hashtext() is deterministic within a server, which is all that is required
--   — the value is recomputed from scratch on every refresh and is never
--   compared against a stored one.
create or replace function public.related_stable_tiebreak(p_id text)
returns real language sql immutable parallel safe as $$
  select ((hashtext(p_id)::bigint + 2147483648)::double precision
          / 4294967296.0)::real;
$$;

comment on function public.related_stable_tiebreak(text) is
  'Deterministic uniform shuffle in [0,1) from a target id. The related_items '
  'tiebreak for regulation and circular: it asserts no quality ordering, it '
  'only removes planner nondeterminism from a block of equal scores. Unbiased '
  'on purpose — alphabetical order was the alternative and it would have '
  'systematically front-loaded one doc-type prefix («نظام…» / «تعميم…»).';


-- ── 3. related_items.tiebreak + the lookup index + the comment refresh ─────

-- Metadata-only on PG11+ (constant default, no rewrite) even at 648 MB. The
-- DEFAULT is what makes the intermediate state safe: every row 143 already
-- wrote reads 0 until its corpus is refreshed, so `score desc, tiebreak desc`
-- degrades to today's `score desc` — never to a WRONG order.
alter table public.related_items
  add column if not exists tiebreak real not null default 0;

-- The index swap. Conditional so a re-apply is a no-op instead of a second
-- rebuild: only drop while the index still has 143's three-column shape.
-- Not CONCURRENTLY — see the apply-cost note in the header.
do $$
begin
  if exists (
    select 1 from pg_indexes
     where schemaname = 'public'
       and indexname  = 'idx_related_items_lookup'
       and indexdef not like '%tiebreak%'
  ) then
    raise notice '145 §3: rebuilding idx_related_items_lookup with tiebreak '
                 '(ACCESS EXCLUSIVE on related_items for a few seconds)';
    execute 'drop index public.idx_related_items_lookup';
  end if;
end $$;

create index if not exists idx_related_items_lookup
  on public.related_items (source_type, source_id, score desc, tiebreak desc);

comment on index public.idx_related_items_lookup is
  'THE read path. Serves the backend''s '
  '`where source_type = ? and source_id = ? order by score desc, tiebreak desc` '
  'as ONE index scan — the two sort keys are in the index in that order, so no '
  'sort node appears above it. Extended from (source_type, source_id, score '
  'desc) in migration 145: on judgment, score alone is a perfect tie inside a '
  'court and the top 7 was arbitrary and unstable between queries.';

-- Existing table/column comments that the new column makes stale.
comment on table public.related_items is
  'Precomputed «اقرأ تاليًا» graph. Same-type only (D2). Stored in BOTH '
  'directions. NO publish state and NO stored rank: rank changes with every '
  'publish, so the reader joins seo_item_meta and orders by '
  'score desc, tiebreak desc (D5/D6). Rebuilt per corpus by '
  'refresh_related_items(); weekly on pg_cron. score = base + bonus is an '
  'invariant — the tiebreak is a SEPARATE column and is never folded in.';

-- MEASURED AFTER APPLYING (2026-08-23): 161 of the 337 canonical guides have
--   most_used_rank NULL, not 0 as this file first guessed — ranks run 4..270
--   over only 176 guides. So ~48% of خدمات targets land on tiebreak 0 together.
--   That is cosmetic here and NOT the judgment problem repeating: خدمات scores
--   come from a continuous cosine base, so exact score ties are rare. Measured:
--   63 (source, score) tie groups across 201 edges, of which the tiebreak
--   resolves all but 2. If most_used_rank coverage ever drops further, give the
--   unranked half related_stable_tiebreak(f.b) scaled into [0, 0.5) and the
--   ranked half (0.5, 1.0], so ranked still wins and unranked stops colliding.
comment on column public.related_items.tiebreak is
  'Ordering key #2, applied after score desc. A property of the TARGET '
  '(denormalized onto every incoming edge so the read stays one index scan), '
  'normalized to [0,1], higher = shown first. judgment: recency of the ruling, '
  'cume_dist over date_gregorian falling back to a Hijri-year date, and exactly '
  '0 for a dateless ruling so it sorts LAST. compliance: '
  'service_guides.most_used_rank, most-used first, 0 when unranked. regulation '
  'and circular: related_stable_tiebreak(target_id), a stable shuffle carrying '
  'no signal. NEVER thresholded and never added to score — only its '
  'monotonicity is meaningful, never its spacing. Defaults to 0, so a corpus '
  'that has not been refreshed since migration 145 simply orders by score.';

comment on column public.related_items.reason is
  'document_relation_both | document_relation_one_way | core_subject_relation | '
  'core_subject_member | service_embedding | topic_bm25 | bonus_only. Audit and '
  'Wave D sampling only — D10 forbids rendering a relation-type chip, because '
  '585 of 746 document_relations rows are single-method guesses. '
  '''service_embedding'' (145) = a خدمات pair scored on services.embedding '
  'cosine; ''topic_bm25'' stays reserved for the تعاميم Wave E seam, which is '
  'still empty. They are different evidence and are never merged.';


-- ── 4. refresh_related_items(p_corpus) — redefined whole ───────────────────
-- 143's functions are `create or replace`, so the whole body is restated here.
-- Diff against 143 §7, branch by branch:
--
--   regulation  + `tiebreak` in the INSERT column list
--               + related_stable_tiebreak(f.b) in the final SELECT
--               (nothing else changes — no CTE is touched)
--   circular    same two lines, same reasoning
--   compliance  + the Wave E seam FILLED: `svec` and a real `topic_base`
--               + reason flips to 'service_embedding' when a base is present
--               + `docs` wrapped to carry the most_used_rank tiebreak
--               + `tiebreak` in the INSERT list and db.tiebreak in the SELECT
--   judgment    + `docs` wrapped to carry the recency tiebreak
--               + `tiebreak` in the INSERT list and db.tiebreak in the SELECT
--
-- The score itself is UNCHANGED everywhere: score = base + bonus, stored iff
-- >= related_floor(). Nothing in this migration re-prices an existing edge on
-- regulation, circular or judgment — those three corpora will come back with
-- exactly the row counts 143 produced, plus a populated tiebreak column.
--
-- ⚠ Note where the tiebreak is read from in each branch. It is a property of
--   the TARGET, i.e. of `b`. On compliance and judgment it rides on the `docs`
--   CTE, which `final` ALREADY joins as `db` — so it costs zero extra joins,
--   even on the judgment branch's 1.45M output rows. On regulation and circular
--   it is a pure function of the id and is computed inline, which keeps those
--   two branches a two-line diff.

create or replace function public.refresh_related_items(p_corpus text)
returns integer
language plpgsql
security definer
-- ⚠ `extensions` IS REQUIRED HERE, and is not tidiness. pgvector's `<=>`
--   operator lives in the `extensions` schema on Supabase; 143 pinned this
--   function to `public` alone, which was harmless until the compliance branch
--   below started using cosine distance. A plpgsql body is only SYNTAX-checked
--   at CREATE time, so 145 applied CLEANLY and then died on the first
--   refresh_related_items('compliance') with
--     «operator does not exist: extensions.vector <=> extensions.vector».
--   `extensions` is owned by supabase_admin and is not writable by any app
--   role, so widening the path does not widen the SECURITY DEFINER blast
--   radius. Anything added to this body that touches a vector needs it.
set search_path = public, extensions
-- ⚠ THIS CLAUSE DOES NOT PROTECT THIS FUNCTION'S OWN BODY (143, learned the
--   hard way on 2026-08-23). statement_timeout is armed when the OUTER
--   statement starts, from the value in force at that moment; a function-local
--   SET changes the setting for later statements, never for the one already
--   running. `select public.refresh_related_items('judgment')` is bounded by
--   the CALLER's timeout — 2 minutes under Supabase's pooler — and the judgment
--   branch takes ~13 minutes. The caller must raise it; §6 has the recipe. The
--   clause is kept because it is the right ceiling for the weekly cron job,
--   whose session inherits no shorter one.
set statement_timeout = '900s'
as $$
declare
  v_count integer := 0;
begin

  -- ══ أنظمة ════════════════════════════════════════════════════════════════
  if p_corpus = 'regulation' then
    delete from public.related_items where source_type = 'regulation';

    insert into public.related_items
      (source_type, source_id, target_type, target_id, score, base, bonus, reason, tiebreak)
    with
    docs as (
      select r.id::text as id,
             public.related_canonical_entity(nullif(btrim(r.entity_ref::text), '')) as entity,
             coalesce(r.sectors, '{}'::text[]) as sectors
        from public.regulations_v2 r
    ),
    ds as (   -- the (doc, sector) inverted index; see 143 §7.2
      select d.id, s.v as sector
        from docs d, unnest(d.sectors) s(v)
       where nullif(btrim(s.v), '') is not null
    ),
    sw as (select w.value, w.weight from public.related_axis_weights w
            where w.corpus = 'regulation' and w.axis = 'sector'),
    ew as (select w.value, w.weight from public.related_axis_weights w
            where w.corpus = 'regulation' and w.axis = 'entity'),

    -- ── base sources (plan §3.3), max() over any duplicate edge row ────────
    b_doc as (
      select e.a, e.b,
             max(case when e.agreement = 'both' then 5.0 else 3.5 end)::real as base
        from public.related_reg_document_edges e
       group by e.a, e.b
    ),
    b_sub as (
      -- 1.5 + 1.5*(score-0.6)/0.4 -> [1.5, 3.0]. Clamped both ends: the ingest
      -- threshold is 0.6 today, and a future re-run at a lower threshold must
      -- not push the base under the 1.2 cluster tier.
      select e.a, e.b,
             least(3.0, greatest(1.5,
               1.5 + 1.5 * (max(e.score) - 0.6) / 0.4))::real as base
        from public.related_reg_subject_edges e
       group by e.a, e.b
    ),
    b_clu as (
      select distinct m1.reg_id as a, m2.reg_id as b, 1.2::real as base
        from public.related_reg_subject_members m1
        join public.related_reg_subject_members m2
          on m2.core_subject_id = m1.core_subject_id
         and m2.reg_id <> m1.reg_id
    ),

    -- ── candidates ─────────────────────────────────────────────────────────
    cand as (
      select u.a, u.b from (
          select a, b from b_doc
        union
          select a, b from b_sub
        union
          select a, b from b_clu
        union
          -- entity generator, guarded (143 §0). On أنظمة this fires only for
          -- entities with n <= 100 documents, so the four biggest issuing
          -- authorities generate nothing at all.
          select d1.id as a, d2.id as b
            from docs d1
            join ew on ew.value = d1.entity
                   and ew.weight >= public.related_gen_floor()
            join docs d2 on d2.entity = d1.entity and d2.id <> d1.id
        union
          -- sector generator, guarded by the FULL sector_term (the HAVING is
          -- the guard; a pair only survives if its shared sectors alone carry
          -- half the floor).
          select p.a, p.b from (
            select x.id as a, y.id as b,
                   least(1.0, (count(*) * (count(*) + 1) / 2.0) * sum(sw.weight))
                     as sector_term
              from ds x
              join ds y  on y.sector = x.sector and y.id <> x.id
              join sw    on sw.value = x.sector
             group by x.id, y.id
          ) p
          where p.sector_term >= public.related_gen_floor()
      ) u
      where u.a is not null and u.b is not null and u.a <> u.b
    ),

    -- Shared sectors for every candidate pair, whatever generated it. Note
    -- this uses ALL shared sectors, including ones far below the generation
    -- threshold: generation filters the GENERATOR, scoring uses everything.
    pair_sec as (
      select c.a, c.b, count(*)::int as k,
             sum(sw.weight)::double precision as w_sum
        from cand c
        join ds x on x.id = c.a
        join ds y on y.id = c.b and y.sector = x.sector
        join sw   on sw.value = x.sector
       group by c.a, c.b
    ),

    scored as (
      select c.a, c.b,
             bd.base as base_doc, bs.base as base_sub, bc.base as base_clu,
             least(2.0,
                   (case when da.entity is not null and da.entity = db.entity
                         then coalesce(ew.weight, 0) else 0 end)
                 + coalesce(least(1.0, (ps.k * (ps.k + 1) / 2.0) * ps.w_sum), 0)
             )::real as bonus
        from cand c
        join docs da on da.id = c.a
        join docs db on db.id = c.b
        left join b_doc    bd on bd.a = c.a and bd.b = c.b
        left join b_sub    bs on bs.a = c.a and bs.b = c.b
        left join b_clu    bc on bc.a = c.a and bc.b = c.b
        left join pair_sec ps on ps.a = c.a and ps.b = c.b
        left join ew          on ew.value = da.entity and da.entity = db.entity
    ),
    final as (
      -- greatest() ignores NULLs, so this is "the max of whichever apply".
      select s.a, s.b,
             coalesce(greatest(s.base_doc, s.base_sub, s.base_clu), 0)::real as base,
             s.bonus,
             case
               when coalesce(greatest(s.base_doc, s.base_sub, s.base_clu), 0) = 0
                 then 'bonus_only'
               when s.base_doc is not null
                    and s.base_doc >= coalesce(s.base_sub, 0)
                    and s.base_doc >= coalesce(s.base_clu, 0)
                 then case when s.base_doc >= 5.0 then 'document_relation_both'
                           else 'document_relation_one_way' end
               when s.base_sub is not null and s.base_sub >= coalesce(s.base_clu, 0)
                 then 'core_subject_relation'
               else 'core_subject_member'
             end as reason
        from scored s
    )
    -- TIEBREAK (145). A stable shuffle, carrying no signal, and both of the
    -- alternatives that DO carry signal were rejected on the merits:
    --   • seo_item_meta.rank (the usage rank from migration 116) is THE hub
    --     ordering key and would be the obvious choice — but 143's D5 contract
    --     is that NOTHING in this graph reads seo_item_meta. Publish state must
    --     not leak into the stored edges, and `rank` is NULL for every
    --     unranked/unpublished نظام, so half the corpus would silently sort
    --     last inside the graph rather than at render time.
    --   • Alphabetical (the wing's own secondary sort) is deterministic but
    --     BIASED: Arabic أنظمة titles almost all open with «نظام» or «لائحة»,
    --     so it would front-load one doc-type prefix in every strip.
    -- If a verified issue-date column is ever confirmed on regulations_v2, this
    -- is the one expression to replace — the judgment branch below is the
    -- worked example of the cume_dist recency shape.
    select 'regulation', f.a, 'regulation', f.b,
           (f.base + f.bonus)::real, f.base, f.bonus, f.reason,
           public.related_stable_tiebreak(f.b)
      from final f
     where (f.base + f.bonus) >= public.related_floor();

  -- ══ تعاميم ═══════════════════════════════════════════════════════════════
  elsif p_corpus = 'circular' then
    delete from public.related_items where source_type = 'circular';

    insert into public.related_items
      (source_type, source_id, target_type, target_id, score, base, bonus, reason, tiebreak)
    with
    docs as (
      -- circulars.entity_ref is this corpus's own key space (5 distinct values,
      -- 296–619 docs each — every one of them is worth ~0 after 143 §0's fix,
      -- which is the correct reading of "both issued by the same ministry").
      select ci.id::text as id,
             public.related_canonical_entity(nullif(btrim(ci.entity_ref::text), '')) as entity,
             coalesce(ci.sectors, '{}'::text[]) as sectors
        from public.circulars ci
    ),
    ds as (
      select d.id, s.v as sector
        from docs d, unnest(d.sectors) s(v)
       where nullif(btrim(s.v), '') is not null
    ),
    sw as (select w.value, w.weight from public.related_axis_weights w
            where w.corpus = 'circular' and w.axis = 'sector'),
    ew as (select w.value, w.weight from public.related_axis_weights w
            where w.corpus = 'circular' and w.axis = 'entity'),

    -- ══════════════════ WAVE E SEAM — topic-BM25 base ══════════════════════
    -- STILL EMPTY. تعاميم have no citations, no clusters and 5 entity values;
    -- one topic sentence per تعميم (search_topics source_type='circular',
    -- 2,119 rows, 1.15/doc) is the only content signal this corpus will ever
    -- have. Until Wave E ships it, تعاميم are BONUS-ONLY.
    --
    -- ⚠ 145 filled the خدمات twin of this seam with vectors, NOT with BM25 —
    -- see the compliance branch. That is not a template for this one: تعاميم
    -- have no embedding of their own, so this seam keeps the plan's original
    -- BM25 contract, INCLUDING its relative normalization.
    --
    -- CONTRACT for the replacement: (a text, b text, base real), one row per
    -- ORDERED pair, BOTH directions, base = 3.0 * bm25 / max_bm25_for_this_
    -- source, i.e. (0, 3.0] normalized per source (plan §3.3 — relative
    -- because BM25 is unbounded and its scale varies with corpus statistics).
    -- Nothing else in this branch changes: `cand` already unions it, `final`
    -- already left-joins it, and `reason` already flips to 'topic_bm25'.
    -- ⚠ Wave E must ALSO emit its own candidates — the axis generators are only
    -- lossless for base = 0 pairs (143 §0), so a topic pair whose base carries
    -- it over the floor has to be generated by the topic side.
    topic_base as (
      select null::text as a, null::text as b, null::real as base where false
    ),
    -- ═══════════════════════════════════════════════════════════════════════

    cand as (
      select u.a, u.b from (
          select a, b from topic_base
        union
          select d1.id as a, d2.id as b
            from docs d1
            join ew on ew.value = d1.entity
                   and ew.weight >= public.related_gen_floor()
            join docs d2 on d2.entity = d1.entity and d2.id <> d1.id
        union
          select p.a, p.b from (
            select x.id as a, y.id as b,
                   least(1.0, (count(*) * (count(*) + 1) / 2.0) * sum(sw.weight))
                     as sector_term
              from ds x
              join ds y  on y.sector = x.sector and y.id <> x.id
              join sw    on sw.value = x.sector
             group by x.id, y.id
          ) p
          where p.sector_term >= public.related_gen_floor()
      ) u
      where u.a is not null and u.b is not null and u.a <> u.b
    ),
    pair_sec as (
      select c.a, c.b, count(*)::int as k,
             sum(sw.weight)::double precision as w_sum
        from cand c
        join ds x on x.id = c.a
        join ds y on y.id = c.b and y.sector = x.sector
        join sw   on sw.value = x.sector
       group by c.a, c.b
    ),
    final as (
      select c.a, c.b,
             coalesce(tb.base, 0)::real as base,
             least(2.0,
                   (case when da.entity is not null and da.entity = db.entity
                         then coalesce(ew.weight, 0) else 0 end)
                 + coalesce(least(1.0, (ps.k * (ps.k + 1) / 2.0) * ps.w_sum), 0)
             )::real as bonus,
             case when coalesce(tb.base, 0) > 0 then 'topic_bm25'
                  else 'bonus_only' end as reason
        from cand c
        join docs da on da.id = c.a
        join docs db on db.id = c.b
        left join topic_base tb on tb.a = c.a and tb.b = c.b
        left join pair_sec   ps on ps.a = c.a and ps.b = c.b
        left join ew            on ew.value = da.entity and da.entity = db.entity
    )
    -- TIEBREAK (145): the same stable shuffle as أنظمة, and it matters MORE
    -- here. تعاميم are bonus-only, so their scores come from a handful of
    -- sector-weight sums and large blocks of candidates tie exactly. The
    -- rejected alternatives are the same two (seo_item_meta.rank is off-limits
    -- under D5; alphabetical front-loads «تعميم…»), plus a third: the wing's
    -- own hub sorts on title, which is precisely the biased option.
    select 'circular', f.a, 'circular', f.b,
           (f.base + f.bonus)::real, f.base, f.bonus, f.reason,
           public.related_stable_tiebreak(f.b)
      from final f
     where (f.base + f.bonus) >= public.related_floor();

  -- ══ خدمات ════════════════════════════════════════════════════════════════
  -- THE BRANCH 145 EXISTS FOR. 143 left this corpus bonus-only and it came back
  -- with 354 edges over 83 of 337 sources; the Wave E seam below is now filled
  -- with services.embedding cosine (see the header, Defect 1).
  elsif p_corpus = 'compliance' then
    delete from public.related_items where source_type = 'compliance';

    insert into public.related_items
      (source_type, source_id, target_type, target_id, score, base, bonus, reason, tiebreak)
    with
    docs as (
      -- The inner select is 143's, unchanged, plus most_used_rank for the
      -- tiebreak. LEFT join to services on purpose: the entity axis and the
      -- corpus membership live on the guide, only the sectors are inherited. A
      -- guide whose service row vanished loses its sectors, not its existence —
      -- the opposite of library_compliance_v's inner join, which is about what
      -- is RENDERABLE. Key space is service_guides.id::text (migration 142),
      -- NOT services.id: the retired 'service' wing left 4,717 rows in the
      -- sidecar under that other key and they are a different corpus entirely.
      --
      -- TIEBREAK (145) = service_guides.most_used_rank, ascending rank = most
      -- used, so the map inverts it: the #1 most-used guide gets 1.0. This is
      -- the ONE corpus where a meaningful tiebreak was available without
      -- touching seo_item_meta — most_used_rank lives on the guide row itself
      -- (142 §confirmed; NULL count was 0 at wing build) and it is already the
      -- /compliance hub's own ordering contract («most used first»), so the
      -- strip and the hub now agree on what "more important" means.
      --   `partition by (most_used_rank is not null)` keeps the unranked out of
      --   the ranked population's denominator; the CASE then sends them to 0 so
      --   they sort last. NOT `order by ... desc nulls last` — cume_dist over a
      --   mixed population would hand the unranked a real value.
      select z.id, z.entity, z.sectors,
             coalesce(
               case when z.most_used_rank is not null
                    then cume_dist() over (
                           partition by (z.most_used_rank is not null)
                           order by z.most_used_rank desc)
               end, 0)::real as tiebreak
        from (
          select g.id::text as id,
                 public.related_canonical_entity(nullif(btrim(g.entity_ref::text), '')) as entity,
                 coalesce(sv.sectors, '{}'::text[]) as sectors,
                 g.most_used_rank
            from public.service_guides g
            left join public.services sv on sv.id = g.service_id
           where coalesce(g.is_canonical, true)
        ) z
    ),
    ds as (
      select d.id, s.v as sector
        from docs d, unnest(d.sectors) s(v)
       where nullif(btrim(s.v), '') is not null
    ),
    sw as (select w.value, w.weight from public.related_axis_weights w
            where w.corpus = 'compliance' and w.axis = 'sector'),
    ew as (select w.value, w.weight from public.related_axis_weights w
            where w.corpus = 'compliance' and w.axis = 'entity'),

    -- ══════════ WAVE E SEAM, FILLED (145) — services.embedding base ════════
    -- INNER joins the whole way down, unlike `docs`: a guide with no service
    -- row, or a service with no embedding, gets no base and keeps its
    -- sector/entity bonus tier. Measured 2026-08-23: 337 of 337 reach one.
    svec as (
      select g.id::text as id, sv.embedding
        from public.service_guides g
        join public.services sv on sv.id = g.service_id
       where coalesce(g.is_canonical, true)
         and sv.embedding is not null
    ),
    -- FULL pairwise cosine. 337 x 336 = 113,232 ordered pairs, ~0.3s. No KNN,
    -- no top-K, no idx_svc_embedding — D6 forbids a top-N per source and an
    -- HNSW index answers a different question ("nearest to this probe") than
    -- the one being asked here. `<=>` is pgvector cosine DISTANCE, so
    -- similarity is 1 - it; same idiom as 101_case_topics_search.sql:147.
    -- Cosine is symmetric and the cross join is unordered, so (a,b) and (b,a)
    -- both fall out naturally — which is the both-directions half of the seam
    -- contract, satisfied without a UNION ALL.
    sim as (
      select x.id as a, y.id as b,
             (1 - (x.embedding <=> y.embedding))::double precision as sim
        from svec x
        join svec y on y.id <> x.id
    ),
    -- The base map. ABSOLUTE, not the plan §3.3 relative form — see the header:
    -- cosine is bounded and comparable across sources, so normalizing by "the
    -- best match for THIS source" would hand a full 3.0 to a guide whose best
    -- neighbour is a mediocre 0.51.
    --     base = 3.0 * (sim - FLOOR) / (MAX - FLOOR),  clamped to (0, 3.0]
    -- Strict `>` on the floor, so the base is never exactly 0 and the seam
    -- contract's (0, 3.0] holds: a pair sitting ON the floor carries no
    -- evidence and must not be labelled as if it did.
    -- greatest(0, …) is belt-and-braces for a future re-fit; nullif guards the
    -- degenerate MAX = FLOOR case.
    topic_base as (
      select s.a, s.b,
             least(3.0, greatest(0.0,
               3.0 * (s.sim - public.related_service_sim_floor())
                   / nullif(public.related_service_sim_max()
                            - public.related_service_sim_floor(), 0)
             ))::real as base
        from sim s
       where s.sim > public.related_service_sim_floor()
    ),
    -- ═══════════════════════════════════════════════════════════════════════

    cand as (
      select u.a, u.b from (
          select a, b from topic_base
        union
          select d1.id as a, d2.id as b
            from docs d1
            join ew on ew.value = d1.entity
                   and ew.weight >= public.related_gen_floor()
            join docs d2 on d2.entity = d1.entity and d2.id <> d1.id
        union
          select p.a, p.b from (
            select x.id as a, y.id as b,
                   least(1.0, (count(*) * (count(*) + 1) / 2.0) * sum(sw.weight))
                     as sector_term
              from ds x
              join ds y  on y.sector = x.sector and y.id <> x.id
              join sw    on sw.value = x.sector
             group by x.id, y.id
          ) p
          where p.sector_term >= public.related_gen_floor()
      ) u
      where u.a is not null and u.b is not null and u.a <> u.b
    ),
    pair_sec as (
      select c.a, c.b, count(*)::int as k,
             sum(sw.weight)::double precision as w_sum
        from cand c
        join ds x on x.id = c.a
        join ds y on y.id = c.b and y.sector = x.sector
        join sw   on sw.value = x.sector
       group by c.a, c.b
    ),
    final as (
      select c.a, c.b,
             coalesce(tb.base, 0)::real as base,
             least(2.0,
                   (case when da.entity is not null and da.entity = db.entity
                         then coalesce(ew.weight, 0) else 0 end)
                 + coalesce(least(1.0, (ps.k * (ps.k + 1) / 2.0) * ps.w_sum), 0)
             )::real as bonus,
             -- 'service_embedding', NOT 'topic_bm25' — different evidence, and
             -- Wave D samples on this column.
             case when coalesce(tb.base, 0) > 0 then 'service_embedding'
                  else 'bonus_only' end as reason,
             db.tiebreak
        from cand c
        join docs da on da.id = c.a
        join docs db on db.id = c.b
        left join topic_base tb on tb.a = c.a and tb.b = c.b
        left join pair_sec   ps on ps.a = c.a and ps.b = c.b
        left join ew            on ew.value = da.entity and da.entity = db.entity
    )
    select 'compliance', f.a, 'compliance', f.b,
           (f.base + f.bonus)::real, f.base, f.bonus, f.reason, f.tiebreak
      from final f
     where (f.base + f.bonus) >= public.related_floor();

  -- ══ أحكام ════════════════════════════════════════════════════════════════
  -- No base axis at all (plan §3.3): base = 0.0 always, court carries the
  -- signal through the bonus. bonus = least(2.0, entity_term + w(court)).
  --
  -- ⚠ THIS IS THE BRANCH THE GUARDS EXIST FOR. An unguarded court self-join is
  --   932M pairs. The generation threshold admits only courts and entities with
  --   w >= FLOOR/2, i.e. n <= ~780 of 30,531 — so التجارية (~22k rows, w ~1e-4)
  --   and وزارة العدل (20,671, w 0.0002) generate NOTHING, which is also why
  --   ~75% of judgment pages will correctly show no strip.
  --
  -- ⚠ AND IT IS THE BRANCH THE TIEBREAK EXISTS FOR (Defect 2). Because court
  --   and entity are both constant inside a court, every surviving candidate
  --   for a given judgment carries the SAME bonus and therefore the same score.
  --   Recency is the only ordering left that a reader would recognise.
  elsif p_corpus = 'judgment' then
    delete from public.related_items where source_type = 'judgment';

    insert into public.related_items
      (source_type, source_id, target_type, target_id, score, base, bonus, reason, tiebreak)
    with
    docs as (
      -- The inner select is 143's, unchanged, plus the effective date.
      --
      -- TIEBREAK (145) = recency of the TARGET ruling, newest first.
      --   Coverage measured 2026-08-23 over 30,531 rows: date_gregorian 19,112,
      --   date_hijri 26,979. Both are handled and so is neither.
      --   • date_gregorian first, guarded by a regex rather than a bare cast.
      --     The guard is type-agnostic (a `date` renders as YYYY-MM-DD under
      --     ::text at the default DateStyle 'ISO, MDY', a text column passes
      --     through unchanged) and, more importantly, it CANNOT THROW: an
      --     unparseable value falls through to the Hijri path instead of
      --     aborting a 13-minute backfill at minute nine. A session running
      --     with a non-ISO DateStyle would degrade the whole corpus to the
      --     Hijri path rather than corrupt it — §7(e)'s second query is the
      --     check that catches that, since it counts dated rulings that came
      --     back with tiebreak 0.
      --   • date_hijri second, via related_hijri_date() — year precision only,
      --     pinned to 1 July. Every ruling known only to its Hijri year lands
      --     on one of ~20 dates and those rows tie with EACH OTHER. That
      --     residual tie is not a defect; it is the precision the data has.
      --   • Neither -> d is NULL -> tiebreak 0, which sorts LAST and is not
      --     NULL (the column is not null). This inversion is the trap the whole
      --     construction is arranged around: Postgres puts NULLs FIRST on a
      --     DESC order, and the judgments hub already carries a `nullsfirst=
      --     False` comment saying this exact bug has bitten this codebase.
      --   • cume_dist, not a min/max rescale: it is rank-based, so one bogus
      --     1899 or 2099 date cannot compress every real ruling into the top
      --     percent of the range. Only monotonicity is ever read.
      --   • `partition by (d is not null)` keeps the dateless out of the dated
      --     population's denominator, so the newest dated ruling is exactly 1.0
      --     and the oldest is 1/~27,000 — still strictly above 0 and still
      --     resolvable in float4 (1/27,000 = 3.7e-5, eps near 1.0 is 1.2e-7).
      --   • greatest()/least() are deliberately NOT used to clamp: they IGNORE
      --     NULLs in Postgres, so `greatest(NULL, date '1900-01-01')` returns
      --     1900-01-01 and would silently turn every dateless ruling into the
      --     OLDEST one instead of the last one.
      select z.id, z.entity, z.court,
             coalesce(
               case when z.d is not null
                    then cume_dist() over (partition by (z.d is not null)
                                           order by z.d)
               end, 0)::real as tiebreak
        from (
          select c.id::text as id,
                 public.related_canonical_entity(c.entity_id::text) as entity,
                 nullif(btrim(c.court), '') as court,
                 case
                   when c.date_gregorian::text ~ '^\d{4}-\d{2}-\d{2}'
                     then substring(c.date_gregorian::text from 1 for 10)::date
                   else public.related_hijri_date(c.date_hijri::text)
                 end as d
            from public.cases c
        ) z
    ),
    cw as (select w.value, w.weight from public.related_axis_weights w
            where w.corpus = 'judgment' and w.axis = 'court'),
    ew as (select w.value, w.weight from public.related_axis_weights w
            where w.corpus = 'judgment' and w.axis = 'entity'),
    cand as (
      select u.a, u.b from (
          -- court generator. w(court) >= FLOOR/2 means n <= ~780 of 30,531, so
          -- التجارية and وزارة العدل never enter — which is the whole reason
          -- this is ~1.5M rows and not 932M.
          select d1.id as a, d2.id as b
            from docs d1
            join cw on cw.value = d1.court
                   and cw.weight >= public.related_gen_floor()
            join docs d2 on d2.court = d1.court and d2.id <> d1.id
        union
          select d1.id as a, d2.id as b
            from docs d1
            join ew on ew.value = d1.entity
                   and ew.weight >= public.related_gen_floor()
            join docs d2 on d2.entity = d1.entity and d2.id <> d1.id
      ) u
      where u.a is not null and u.b is not null and u.a <> u.b
    ),
    final as (
      select c.a, c.b,
             0::real as base,
             least(2.0,
                   (case when da.entity is not null and da.entity = db.entity
                         then coalesce(ew.weight, 0) else 0 end)
                 + (case when da.court is not null and da.court = db.court
                         then coalesce(cw.weight, 0) else 0 end)
             )::real as bonus,
             'bonus_only'::text as reason,
             db.tiebreak            -- the TARGET's recency; db is already joined
        from cand c
        join docs da on da.id = c.a
        join docs db on db.id = c.b
        left join ew on ew.value = da.entity and da.entity = db.entity
        left join cw on cw.value = da.court  and da.court  = db.court
    )
    select 'judgment', f.a, 'judgment', f.b,
           (f.base + f.bonus)::real, f.base, f.bonus, f.reason, f.tiebreak
      from final f
     where (f.base + f.bonus) >= public.related_floor();

  else
    raise exception 'refresh_related_items: unknown corpus %', p_corpus;
  end if;

  get diagnostics v_count = row_count;
  return v_count;
end $$;

comment on function public.refresh_related_items(text) is
  'Rebuilds public.related_items for one corpus (regulation|circular|compliance'
  '|judgment) and returns the row count. Reads related_axis_weights, so '
  'refresh_related_axis_weights() must have run at least once. Same-type edges '
  'only (D2), both directions, everything above related_floor() — no top-N, no '
  'publish filter, no rank (D5/D6). Writes `tiebreak`, the target-property '
  'ordering key added in 145: recency on judgment, most_used_rank on '
  'compliance, a stable shuffle on regulation/circular. The compliance branch '
  'scores on services.embedding cosine (145) and is the reason that column can '
  'no longer be dropped without reverting this branch.';


-- ── 5. GRANTS ──────────────────────────────────────────────────────────────
-- `create or replace` preserves an existing function's ACL, so the re-issued
-- revokes below are no-ops on a database where 143 already ran. They are kept
-- because they are cheap and because the new functions genuinely need them:
-- everything here is reachable through the PostgREST role graph by default, and
-- there is an OPEN finding that the anon key can read corpus tables directly
-- (project_anon_postgrest_corpus_exposure).
--
-- No table grant is needed for the new column: 143's `grant select on
-- public.related_items to service_role` is table-level and covers every column
-- added afterwards.

revoke all on function public.refresh_related_items(text)        from public, anon, authenticated;
revoke all on function public.related_hijri_year(text)           from public, anon, authenticated;
revoke all on function public.related_hijri_date(text)           from public, anon, authenticated;
revoke all on function public.related_stable_tiebreak(text)      from public, anon, authenticated;
revoke all on function public.related_service_sim_floor()        from public, anon, authenticated;
revoke all on function public.related_service_sim_max()          from public, anon, authenticated;

-- The knobs stay executable for the service role, same as 143's three: Wave D
-- reads them while sampling, and a sample that hardcodes 0.50 instead of
-- calling the function is a sample that silently goes stale after a retune.
grant execute on function public.related_service_sim_floor() to service_role;
grant execute on function public.related_service_sim_max()   to service_role;


-- ============================================================================
-- ── 6. NO BACKFILL IN THIS FILE. RUN THESE BY HAND, IN THIS ORDER. ─────────
-- ============================================================================
-- Deliberate. 143 put its five refreshes inline at §9, and that is exactly what
-- makes re-applying 143 a 13-minute operation with a 2-minute pooler timeout
-- sitting on top of it. Applying THIS file is DDL only: seconds, plus the index
-- rebuild.
--
-- Until each corpus is refreshed it keeps 143's edges with tiebreak = 0, so the
-- read degrades to `order by score desc` — today's behaviour exactly. Nothing
-- is broken by refreshing late; خدمات stays starved and أحكام stays arbitrary
-- until you do.
--
-- related_axis_weights does NOT need rebuilding: this migration does not change
-- any weight, and the خدمات fix works by adding a base axis rather than by
-- re-pricing the scarcity axes. Running refresh_related_axis_weights() anyway
-- is harmless.
--
--   STEP 1 — خدمات. Seconds. Fixes Defect 1. Do this one first: it is the
--   cheapest, and its row count is the headline number to record in the plan.
--
--     select public.refresh_related_items('compliance');
--     -- expect ~2,000–2,800 edges over ~300–337 sources
--     -- (143 left it at 354 edges over 83)
--
--   STEP 2 — أنظمة and تعاميم. Seconds to about a minute each. Same edges as
--   143 produced, now carrying a tiebreak.
--
--     select public.refresh_related_items('regulation');   -- expect ~77,612
--     select public.refresh_related_items('circular');     -- expect ~7,326
--
--   STEP 3 — أحكام. ~13 MINUTES (12:56 measured on 143, 1,456,576 rows).
--   ⚠ DO NOT run this from the SQL editor or any pooled client: the Supabase
--   pooler cuts the caller at 120s, the function's own `set statement_timeout`
--   cannot extend a statement that is already running, and the rollback is
--   SILENT — related_items simply comes back with no judgment rows. This cost
--   143 two attempts. Run it server-side as a pg_cron one-shot, scheduled a
--   couple of minutes out:
--
--     select cron.schedule(
--       'related_items_judgment_oneshot', '<MM> <HH> * * *',
--       $c$ set statement_timeout = '900s';
--           set work_mem = '256MB';
--           select public.refresh_related_items('judgment'); $c$);
--
--     -- watch it (it will say 'running' for ~13 minutes, then 'succeeded'):
--     select jobid, status, start_time, end_time, return_message
--       from cron.job_run_details
--      where jobid = (select jobid from cron.job
--                      where jobname = 'related_items_judgment_oneshot')
--      order by start_time desc limit 5;
--
--     -- then, and only then:
--     select cron.unschedule('related_items_judgment_oneshot');
--
--   Plain `SET`, never `SET LOCAL` — outside a transaction block that is a
--   no-op with a warning.
--
--   STEP 4 — run §7 below. Then purge the ISR cache for the four wings, or the
--   baked pages keep serving yesterday's strips (isr_bake_docker_cache_trap;
--   percent-encode Arabic slugs or the 200 lies —
--   isr_revalidate_percent_encoding).
--
-- The weekly job (143 §8, 'related_items_refresh_weekly') needs no change: it
-- calls the same five statements and picks all of this up automatically on the
-- next Sunday 03:40 run. Its compliance statement now does 113,232 vector
-- comparisons instead of nothing, which adds well under a second to a job whose
-- judgment statement already runs for 13 minutes.
--
-- ⚠ ONE NEW WAY FOR THAT JOB TO FAIL WHOLESALE. Its five statements run in
--   sequence in one cron session, and `compliance` comes BEFORE `judgment`. If
--   services.embedding is ever dropped (reg_search_unified_topics D6), the
--   compliance statement raises, the job aborts, and the judgment refresh never
--   runs — the failure would present as a stale judgment graph, not as a
--   missing خدمات axis. See the collision warning in the header.
-- ============================================================================


-- ============================================================================
-- ── 7. VERIFICATION — run AFTER the refreshes in §6, not at apply time ─────
-- ============================================================================
--
-- (a) The score invariant. THE production check; must return 0.
--     A tiebreak folded into score would break exactly this.
--
--     select count(*) from public.related_items
--      where abs(score - (base + bonus)) > 0.001;
--
-- (b) The tiebreak invariant. Must return 0 rows. [0,1], never NULL.
--
--     select count(*) from public.related_items
--      where tiebreak < 0 or tiebreak > 1;
--
-- (c) Defect 1 closed. `sources` was 83 of 337; expect ~300+.
--
--     select count(*) as edges,
--            count(distinct source_id) as sources,
--            round(avg(score)::numeric, 3) as avg_score,
--            min(score), max(score)
--       from public.related_items where source_type = 'compliance';
--
--     select reason, count(*), round(min(base)::numeric,3),
--            round(max(base)::numeric,3)
--       from public.related_items where source_type = 'compliance'
--      group by 1 order by 2 desc;
--     -- expect 'service_embedding' to dominate and 'bonus_only' to be the tail
--
--     -- the 27ish guides the similarity floor leaves without a base axis:
--     select count(*) from public.service_guides g
--      where coalesce(g.is_canonical, true)
--        and not exists (select 1 from public.related_items ri
--                         where ri.source_type = 'compliance'
--                           and ri.source_id = g.id::text
--                           and ri.base > 0);
--
-- (d) Defect 2 closed. The largest tax chamber used to return 532 candidates
--     all scoring 0.161 in planner order. Pick any judgment that has a strip
--     and confirm the top 7 is now newest-first and REPEATABLE:
--
--     with s as (
--       select source_id from public.related_items
--        where source_type = 'judgment'
--        group by 1 order by count(*) desc limit 1)
--     select ri.target_id, ri.score, ri.tiebreak,
--            c.date_gregorian, c.date_hijri
--       from public.related_items ri
--       join s on s.source_id = ri.source_id
--       join public.cases c on c.id::text = ri.target_id
--      where ri.source_type = 'judgment'
--      order by ri.score desc, ri.tiebreak desc
--      limit 7;
--     -- run it twice; the seven rows must be identical both times
--
-- (e) Dateless rulings sort last, and no dated one was mistaken for dateless.
--     The second query must return 0.
--
--     select count(*) filter (where tiebreak = 0) as dateless_targets,
--            count(*) as edges
--       from public.related_items where source_type = 'judgment';
--
--     select count(*) from public.related_items ri
--       join public.cases c on c.id::text = ri.target_id
--      where ri.source_type = 'judgment' and ri.tiebreak = 0
--        and (c.date_gregorian is not null
--             or public.related_hijri_year(c.date_hijri::text) is not null);
--
-- (f) The read path is still ONE index scan with no sort node on top:
--
--     explain (analyze, buffers)
--     select target_id, score, tiebreak from public.related_items
--      where source_type = 'judgment' and source_id = '<some id>'
--      order by score desc, tiebreak desc limit 40;
--     -- want: Index Scan using idx_related_items_lookup. A "Sort" node above
--     -- the scan means the index swap in §3 did not take.
--
-- (g) 143's own four invariants still hold (same-type, no self-edge, floor):
--
--     select count(*) from public.related_items
--      where source_type <> target_type
--         or source_id = target_id
--         or score < public.related_floor();          -- must be 0
--
-- (h) Record the new numbers in .claude/plans/read_next_related_items.md, in
--     the §8-style table at the top of that file:
--
--     select source_type, count(*) as edges,
--            count(distinct source_id) as sources,
--            count(*) filter (where base = 0) as bonus_only,
--            round(min(score)::numeric,3) as lo,
--            round(max(score)::numeric,3) as hi
--       from public.related_items group by 1 order by 1;
--
-- ============================================================================
-- ⚠ NOT AUTO-APPLIED. Files in this directory are run by hand (Supabase SQL
-- editor / MCP apply_migration); nothing in the repo executes them. Apply this
-- file as ONE script, then work through §6 and §7. Apply it BEFORE deploying
-- any backend that orders by `tiebreak` — a column that does not exist is a
-- 500, and this repo has hit the migration-before-deploy trap twice.
-- ============================================================================
